### ISSUE TITLE
Creating a physical geometry in a model

### ISSUE THREAD

**Issue by lijiayi0921** [iTwin/pcf#17]
Hi,
I'm trying to insert geometries into an empty iTwin model.
Inspired by the example I try to draw some boxes. The connector program passes, changes are made in the iModel.
A new named version is then created with the last change. But when opened it says "This iModel has no data to view".
Elements can be found in the tree, but nothing is in the 3D view.

Below is my implementation.

What did I do wrong ?
Thank you in advance

    /** Creates a GeometryStream containing a single box entry. */
    function createBoxGeom(size: Point3d): common.GeometryStreamProps {
      const builder = new common.GeometryStreamBuilder();
      builder.appendGeometry(Box.createDgnBox(
        Point3d.createZero(), Vector3d.unitX(), Vector3d.unitY(), new Point3d(0, 0, size.z),
        size.x, size.y, size.x, size.y, true,
      )!);
      return builder.geometryStream;
    }
    
    export const Component: pcf.ElementDMO = {
      // represents the sheet named "Component" in ./assets/sample.xlsx
      irEntity: "Component",
      // define a dynamic component 
      ecElement: {
        name: "Component",
        baseClass: PhysicalElement.classFullName,
      },
      modifyProps(props: any, instance: pcf.IRInstance) {
        // modify default props assigned to current EC Entity
        props.userLabel = instance.key;
        props.geom = createBoxGeom(Point3d.create(1, 1, 1));
      },
      categoryAttr: "CategoryName",
    };

**Comment by jackson-at-bentley** [comment]
Closing because the issue was resolved on `core`.
