### ISSUE TITLE
Configure host

### ISSUE THREAD

**Issue by lmborione** [iTwin/pcf#21]
Hello 

When I run my pcf connector, I got an error "Error: listen EADDRINUSE: address already in use" because my application was already running on the same port.
I managed to bypass this issue by setting `redirectUri: 'http://localhost:3001/signin-callback'` to the hubargs for development. But when deployed, my application will be inside a docker container behind a proxy and this solution will not be available anymore.

How could we configure the host url and port on which the pcf is listening ? (which is different from the public url set as redirectUri).
@zachzhu2016 

Thanks.
LMB.

**Comment by jchick-bentley** [comment]
@lmborione I assigned this issue to myself.  It may be necessary to refactor PCF to use a different credential workflow in order to bypass this issue when running inside a docker container.  I will follow up after I do some investigation.
